package dat.enums;

public enum MedicalHistory {
    VACCINATED,
    DEWORMED,
    SPAYED,
    NEUTERED,
    MICROCHIPPED,
    FLEA_TREATED,
    HEARTWORM_TREATED,
    VACCINATED_AND_DEWORMED,
    DIGITAL_HEALTH_CERTIFICATE,
    DIGESTION_PROBLEMS,
    ALLERGIES,
    DIABETES,
    HEART_CONDITION,
    DIETARY_RESTRICTIONS,
    OTHER;
}
