### Retrieve all animals
GET http://localhost:7000/api/animals
Content-Type: application/json

### Retrieve a specific animal by id
GET http://localhost:7000/api/animals/1
Content-Type: application/json

### Populate animals into the DB
GET http://localhost:7000/api/animals/populate
Content-Type: application/json

### Body
{
  "msg": "Data populated"
}

### Create a new animal
POST http://localhost:7000/api/animals
Content-Type: application/json

### Body
{
  "name": "Charlie",
  "species": "Dog",
  "age": "3",
  "userId": "1"
}

### Response
{
  "msg": "Animal created",
  "animal": {
    "id": "1",
    "name": "Charlie",
    "species": "Dog",
    "age": "3",
    "userId": "1"
  }
}

### Update animal details
PUT http://localhost:7000/api/animals/1
Content-Type: application/json

### Body
{
  "name": "Charlie",
  "species": "Dog",
  "age": "4"
}

### Response
{
  "msg": "Animal updated",
  "animal": {
    "id": "1",
    "name": "Charlie",
    "species": "Dog",
    "age": "4",
    "userId": "1"
  }
}

### Delete a specific animal
DELETE http://localhost:7000/api/animals/1
Content-Type: application/json

### Response
{
  "msg": "Animal deleted"
}