
### Retrieve all clients
GET {{url}}/api/client
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve a specific client by ID (ID=1)
GET {{url}}/api/clients/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve animals of a specific client (ID=1)
GET {{url}}/api/clients/1/animals
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Create a new client
POST {{url}}/api/clients
Content-Type: application/json

{
    "username": "newuser",
    "password": "password123",
    "email": "newuser@example.com"
}

### Update a specific client by ID (ID=1)
PUT {{url}}/api/clients/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "username": "updateduser",
    "email": "updateduser@example.com"
}

### Delete a specific client by ID (ID=1)
DELETE {{url}}/api/clients/1
Accept: application/json
Authorization: Bearer {{jwt_token}}
