
###
GET http://localhost:7071/api/clients
Accept: application/json

###
GET http://localhost:7071/api/clients/1
Accept: application/json

###
POST http://localhost:7071/api/clients
Content-Type: application/json

{
  "fullName": "Manuel Neuer",
  "email": "Manuel@example.com",
  "phone": "+45 12 34 56 78",
  "gender": "MALE"
}

###
PUT http://localhost:7071/api/clients/1
Content-Type: application/json

{
  "fullName": "Ninna Jensen",
  "email": "Ninna@example.com",
  "phone": "+45 12312322",
  "gender": "FEMALE"
}

###
DELETE http://localhost:7071/api/clients/1
Accept: application/json