### Retrieve all clinics
GET {{url}}/api/clinics
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve all veterinarians
GET {{url}}/api/clinics/veterinarians
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve a specific clinic by ID (ID=1)
GET {{url}}/api/clinics/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve clinic opening hours
GET {{url}}/api/clinics/openinghours
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Create a new clinic (ID=11)
POST {{url}}/api/clinics/11
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Create a new veterinarian (ID=11)
POST {{url}}/api/clinics/veterinarians/11
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Add opening hours to a clinic (ID=5)
POST {{url}}/api/clinics/5/openinghours
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Update a specific clinic by ID (ID=1)
PUT {{url}}/api/clinics/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Delete a specific veterinarian (ID=1)
DELETE {{url}}/api/clinics/veterinarians/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Delete a specific clinic by ID (ID=1)
DELETE {{url}}/api/clinics/1
Accept: application/json
Authorization: Bearer {{jwt_token}}
