
### Populate the database with some clinic data
GET {{url}}/api/clinics/populate
Accept: application/json

### Retrieve all clinics
GET {{url}}/api/clinics
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve all veterinarians
GET {{url}}/api/clinics/veterinarians
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve a specific clinic by ID (ID=1)
GET {{url}}/api/clinics/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Retrieve clinic opening hours
GET {{url}}/api/clinics/openinghours
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Create a new clinic (ID=1)
POST {{url}}/api/clinics/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Create a new veterinarian (ID=1)
POST {{url}}/api/clinics/veterinarians/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Add opening hours to a clinic (ID=1)
POST {{url}}/api/clinics/1/openinghours
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Update a specific clinic by ID (ID=1)
PUT {{url}}/api/clinics/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### Delete a specific veterinarian (ID=1)
DELETE {{url}}/api/clinics/veterinarians/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Delete a specific clinic by ID (ID=1)
DELETE {{url}}/api/clinics/1
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Get all clinics on duty
GET http://localhost:7071/api/clinicsonduty
Accept: application/json

