### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new client - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "client",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "client",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to client
POST {{url}}/auth/client/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "Vetenarian"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Reset token
GET {{url}}/auth/test/

> {%
    client.global.set("jwt_token", null);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###